service: pizzaApp

build:
  esbuild:
    bundle: true
    minify: true
    external:
      - '@aws-sdk/client-sqs'
      - "@aws-sdk/lib-dynamodb"

provider:
  name: aws
  profile: labs
  runtime: nodejs22.x
  architecture: arm64
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - Fn::GetAtt:
                - pendingOrderQueue
                - Arn
            - Fn::GetAtt:
                - ordersToSendQueue
                - Arn
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:GetItem"
          Resource:
            - Fn::GetAtt:
                - ordersTable
                - Arn

functions:
  createOrder:
    handler: services/create-order.createOrder
    environment:
      PENDING_ORDER_QUEUE_URL:
        Ref: pendingOrderQueue
      ORDERS_TABLE_NAME:
        Ref: ordersTable
    events:
      - httpApi:
          path: /api/orders
          method: POST
  getOrder:
    handler: services/get-order.getOrder
    environment:
      ORDERS_TABLE_NAME:
        Ref: ordersTable
    events:
      - httpApi:
          path: /api/orders/{id}
          method: GET
  prepareOrder:
    handler: services/prepare-order.prepareOrder
    environment:
      ORDERS_TABLE_NAME:
        Ref: ordersTable
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - pendingOrderQueue
              - Arn
          batchSize: 1
  sendOrder:
    handler: services/send-order.sendOrder
    environment:
      ORDERS_TO_SEND_QUEUE_URL:
        Ref: ordersToSendQueue
    events:
    #   - httpApi:
    #       path: /api/send-order
    #       method: POST
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - ordersTable
              - StreamArn
          filterPatterns:
            - eventName:
                - MODIFY
          batchSize: 1
  deliverOrder:
    handler: services/deliver-order.deliverOrder
    environment:
      ORDERS_TABLE_NAME:
        Ref: ordersTable
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ordersToSendQueue
              - Arn
          batchSize: 1


resources:
  Resources:
    pendingOrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: pending-orders-queue
    ordersToSendQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: orders-to-send-queue
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orders
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES